### ISSUE TITLE
Gratitude

### ISSUE THREAD

**Issue by Murkin-Kyiv** [PE5PVB/si4713#2]
Thank You for your library!!! Very good job. It helped me a lot in developing the encoder for RDS pagers. Have a nice day !

https://github.com/user-attachments/assets/75ccff75-0579-4ac7-b879-3c9ca6ab6359
https://github.com/user-attachments/assets/a7cfd50a-8552-4552-b4e2-e06de5962d45

**Comment by PE5PVB** [comment]
Good job!
